# Generated by Django 3.2.7 on 2021-10-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_investment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
