# Generated by Django 3.2.7 on 2021-10-02 17:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.IntegerField(choices=[(1, 'сум')], default=1)),
                ('period', models.PositiveSmallIntegerField(help_text='Кол-во месяцев для рассрочки')),
                ('percentage', models.FloatField(help_text='Процент надбавки')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('installment_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.installmentrate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.IntegerField(choices=[(1, 'сум')], default=1)),
                ('transaction', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateField()),
                ('settled_date', models.DateTimeField()),
                ('is_payed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
            ],
        ),
    ]
